version: '3'
services:
  flask-app:
    build: ./flask_server # Flask Dockerfile 위치
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=ssafy
      - MYSQL_DB=ssafy

  mysql-db:
    image: mysql:8.0.32
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ssafy
      - MYSQL_DATABASE=ssafy