import type { Metadata } from "next";
import Recoil from "@/recoil";
import ReactQuery from "@/react-query";
import RootStyleRegistry from "@/lib/registry";
import AuthSession from "@/Oauth/AuthSession";
import { GlobalCssProvider } from "@/styles/GlobalCSSProvider";
import React from "react";


export const metadata: Metadata = {
  title: "당신의집사",
  description: "Generated by create next app",
};

declare global {
  interface Window {
      kakao: any;
  }
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <head></head>
      <body>
        <script src="https://static.nid.naver.com/js/naveridlogin_js_sdk_2.0.2.js"></script>
        <script
        type="text/javascript"
        src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAOMAP_APPKEY}&autoload=false&libraries=services,clusterer`}></script>
        <Recoil>
          <ReactQuery>
            <AuthSession>
              <RootStyleRegistry>
                <GlobalCssProvider>
                  {children}
                </GlobalCssProvider>
              </RootStyleRegistry>
            </AuthSession>
          </ReactQuery>
        </Recoil>
      </body>
    </html>
  );
};

export default RootLayout;
