spring:
    jpa:
        properties:
          hibernate:
            format_sql: true
            show_sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create
        defer-datasource-initialization: true

        open-in-view: false # HTTP Connection setting

    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:

# JWT setting
jwt:
    issuer: FinancialInnovationCrew
    secret_key: ca972315c2dd67fe07bc289e0280a9c103566f27409416e2249ab7bfd233398c0154cdac5e2b81661576b32ecfb5c2c17d7c5112776a940fb73498171b40e1cb
    access_expiration_ms: 10000000
    refresh_expiration_ms: 2592000000

server:
    port: 5000

oauth:
    naver:
        id: "RmJYEr9vg1ZjQUZrYc2P"
        secret: "49govNvOqT"
    kakao:
        id: "4765b472873cc9716940578b8f5ed7f5"
        secret: "7bdqzxWe5szrZZ0eJMe6sjvu56KsyFxX"
    google:
        id: "467033647312-n87e1g3gd4t76t33j08p5bg8ur79gp63.apps.googleusercontent.com"
        secret: "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"